services:
  postgres:
    image: postgres:16-alpine
    container_name: happy-pet-shop-db
    environment:
      POSTGRES_DB: happy_pet_shop
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d happy_pet_shop"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - happy-pet-shop-network

  redis:
    image: redis:7-alpine
    container_name: happy-pet-shop-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - happy-pet-shop-network

  app:
    build: .
    container_name: happy-pet-shop
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/happy_pet_shop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_KEY: ZXZlbnR0aHJlYWRvbGRub25lZmVuY2VmYWlybHl0b3dlcmFiaWxpdHlmaW5kYmFsbHM\=
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - happy-pet-shop-network

volumes:
  postgres_data:

networks:
  happy-pet-shop-network:
    driver: bridge
