recommendation:
  service:
    url: ${RECOMMENDATION_SERVICE_URL:http://localhost:8000}

moderation:
  base-url: ${MODERATION_SERVICE_URL:http://localhost:8888}

toxic:
  base-url: ${TOXIC_SERVICE_URL:http://localhost:8000}

sentiment:
  base-url: ${SENTIMENT_SERVICE_URL:http://localhost:5000}

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.0-flash
  embedding-model: text-embedding-004
